version: "3.8"
services:
  mongodb:
    image: mongo:5.0.5
    ports:
      - "27017:27017"
  restaurant-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongodb
    depends_on:
      - mongodb